---
- name: "create backend dir"
  file:
    path: ~/backend-app
    state: directory

- name: "Extract backend artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Start backend app"
  shell: |
    cd ~/backend-app
    npm i
    cd dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print_message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu