---
- name: "create backend dir"
  file:
    path: ~/backend-app
    state: directory

- name: "Extract backend artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Start backend app"
  args:
    chdir: ~/backend-app/dist
  shell: |
      echo $TYPEORM_ENTITIES
      echo $TYPEORM_HOST
      npm install
      pm2 stop default
      pm2 start npm -- start 