---
- name: "create backend dir"
  file:
    path: ~/backend-app
    state: directory

- name: "Extract backend artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Start backend app"
  args:
    chdir: ~/backend-app/dist
  environment:
    # Get the environment variables from CircleCI and add to the EC2 instance
    ENVIRONMENT: production
    NODE_ENV: production
    VERSION: "1"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js" 
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
  shell: |
    npm i
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print_message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu