---
- name: "create backend dir"
  file:
    path: ~/backend-app
    state: directory

- name: "Extract backend artifacts"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Start backend app"
  shell: |
      cd ~/backend-app
      npm i
      cd dist
      pm2 stop default
      pm2 start main.js